# Generated by Django 4.2.30 on 2026-05-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='update',
            new_name='updated',
        ),
    ]
